/*
========================================================
Module        : Module 5 - Real World Systems
Project       : Payroll Processing System
Title         : PL/SQL - Calculate Net Salary using Function
Course        : DBMS Lab (BCS551)
DB            : Oracle 21c XE
Schema        : PAYROLL
========================================================
Concepts covered:
- SET SERVEROUTPUT ON for displaying PL/SQL output
- Anonymous PL/SQL block using DBMS_OUTPUT.PUT_LINE
- CREATE OR REPLACE FUNCTION
- Function parameters using %TYPE
- Local variables using %TYPE
- CONSTANT variable declaration
- SELECT INTO statement inside PL/SQL
- Arithmetic calculations in PL/SQL
- RETURN statement from a function
- Calling a PL/SQL function using SELECT
========================================================
Salary Formula:
Net_Salary = Basic_Salary + HRA + Travel_Allowance
             - PF_Deduction - Tax_Deduction

Where:
- HRA            = 20% of Basic_Salary
- Travel         = Rs. 2000 (fixed)
- PF             = 12% of Basic_Salary
- Tax            = 10% of Basic_Salary
========================================================


 ======================================================
 1. Enable DBMS_OUTPUT
 ======================================================
 SERVEROUTPUT ON allows Oracle SQL*Plus/SQL Developer
 to display messages generated by DBMS_OUTPUT.PUT_LINE.
*/

SET SERVEROUTPUT ON

/*
 ======================================================
 2. Test PL/SQL Output
 ======================================================
 This is an anonymous PL/SQL block.
 It simply verifies that PL/SQL output is working.
*/

BEGIN
    DBMS_OUTPUT.PUT_LINE('HELLO PL/SQL! FROM PAYROLL');
END;
/

/*
 ======================================================
 3. Create Function: CALCULATE_NET_SALARY
 ======================================================
 This function calculates an employee's net salary
 using the employee's Basic_Salary stored in EMPLOYEE.

 CREATE OR REPLACE means:
 - CREATE the function if it does not exist.
 - REPLACE the existing function if it already exists.
*/

CREATE OR REPLACE FUNCTION calculate_net_salary (
    p_employee_id IN EMPLOYEE.Employee_ID%TYPE
    -- %TYPE makes the parameter datatype match
    -- EMPLOYEE.Employee_ID automatically.
)
RETURN NUMBER
IS

    -- Local variable to store Basic_Salary.
    -- %TYPE keeps its datatype synchronized with
    -- EMPLOYEE.Basic_Salary.
    v_basic_salary  EMPLOYEE.Basic_Salary%TYPE;

    -- Variables used for individual salary components.
    v_hra           NUMBER;

    -- CONSTANT means its value cannot be changed
    -- during function execution.
    v_travel        CONSTANT NUMBER := 2000;

    v_pf            NUMBER;
    v_tax           NUMBER;
    v_net_salary    NUMBER;

BEGIN
    /*
     ==================================================
     Step 1: Fetch Employee Basic Salary
     ==================================================
     SELECT INTO retrieves the Basic_Salary of the
     employee whose Employee_ID is passed to the function.
    
     The fetched value is stored in v_basic_salary.
     */

    SELECT Basic_Salary
    INTO v_basic_salary
    FROM EMPLOYEE
    WHERE Employee_ID = p_employee_id;

    /*
     ==================================================
     Step 2: Calculate Salary Components
     ==================================================
    */
    -- HRA = 20% of Basic Salary
    v_hra := (v_basic_salary * 20) / 100;

    -- PF = 12% of Basic Salary
    v_pf := (v_basic_salary * 12) / 100;

    -- Tax = 10% of Basic Salary
    v_tax := (v_basic_salary * 10) / 100;

    /*
     ==================================================
     Step 3: Calculate Net Salary
     ==================================================
     Formula:
     Net Salary = Basic Salary + HRA + Travel
                  - PF - Tax
    */

    v_net_salary := v_basic_salary
                    + v_hra
                    + v_travel
                    - v_pf
                    - v_tax;
    /*
     ==================================================
     Step 4: Return Calculated Net Salary
     ==================================================
     RETURN sends the calculated value back to the
     statement that called the function.
    */     

    RETURN v_net_salary;

END;
/

/*
 ======================================================
 4. Calculate Net Salary for All Employees
 ======================================================
 The function is called once for every employee.

 Employee_ID is passed as the function parameter and
 the calculated salary is displayed along with
 the employee's name.
*/

SELECT
    EMP_NAME,
    calculate_net_salary(Employee_ID) AS Calculated_Net_Salary
FROM EMPLOYEE;

/*
 ======================================================
 5. Calculate Net Salary for a Specific Employee
 ======================================================
 Here, Employee_ID 12938981 is passed manually
 to the function.

 DUAL is Oracle's built-in single-row table used when
 we want to execute an expression or function without
 selecting data from a user table.
*/

SELECT calculate_net_salary(12938981)
FROM dual;